on join:
	wait 3 seconds
	unlockAchievement("firstJoin", player)

on region enter:
	if event-region is "staffroom" parsed as region:
		unlockAchievement("staffRoom", player)

on region enter:
	if event-region is "darkDownHere" parsed as region:
		unlockAchievement("darkDownHere", player)

on region enter:
	if event-region is "underTheSea" parsed as region:
		unlockAchievement("underTheSea", player)