on right click on entity:
	if name of entity is "CIT-6ceb2db4dec9":
		{unlocked::6::%player's uuid%} is true:
			{sensei::%player's uuid%} is not set:
				quest(player, 1, 3)
				play sound "block.note_block.pling" to player
				send "&e&lBob Sensei &7> &aHey student, I think it's time for you to start earning some tokens. Everytime you click from now on will have a small chance of giving you a token. Use these tokens to get fun suffixes in the chat! Oh and who knows... Maybe I will add something else in the future..." to player
				set {tokeneligible::%player's uuid%} to true
				send title "&a&lUnlocked: Tokens!" with subtitle "&e+⛁10 tokens" to player
				add 10 to {tokens::%player's uuid%}
				set {sensei::%player's uuid%} to true
				wait 3 second
				quest(player, 2, 3)
			else:
				send "&a[ You can now get tokens by clicking ]" to player
		else:
			send "&cCome back when you have unlocked The Dojo." to player
	if name of entity is "CIT-ca940cd53701":
		{nameless::%player's uuid%} is not set:
			quest(player, 1, 3)
			send "&e&lNameless Man &7> &aHowdy %player%&a, I'm trying to find a fitting name for myself. However, in order for me to do that I need to be inspired. And you know what's inspirational? That's right, &cPharaoh's Treasure&a. If only I could get my hands on it..." to player
			play sound "block.note_block.pling" to player
			wait 3 second
			send title "&a&lQuest Started:" with subtitle "&aFind and give Nameless Man &cPharaoh's Treasure&a."
			play sound "block.amethyst_block.hit" to player
			give player glowing pink dye named "&6Quest ##1 &7: &e&lThe Nameless Man" with lore "&aFind and give Nameless Man ""&cPharaoh's Treasure&a"""
			set {nameless::%player's uuid%} to true
			quest(player, 2, 3)
		else:
			send "&aFind and give Nameless Man ""&cPharaoh's Treasure&a""." to player
			
	if name of entity is "&6&lPharaoh":
		{nameless::%player's uuid%} is true:
			{pharaohn::%player's uuid%} is true:
				send "&e&lPharaoh &7> &aScram weakling!" to player
				play sound "entity.villager.no" to player
				stop
			set {pharaohn::%player's uuid%} to true
			quest(player, 1, 4)
			send "&e&lPharaoh &7> &aWho let this peasant in my holy temple!" to player
			play sound "block.note_block.pling" to player
			wait 2 second
			send "&e&lPharaoh &7> &aYOU WANT MY TREASURE!?" to player
			play sound "block.note_block.pling" to player
			wait 0.5 second
			send "&e&lPharaoh &7> &aPFFT. Scram weakling." to player
			play sound "entity.villager.no" to player#block.note_block.pling
			quest(player, 1, 3)
	if name of entity is "&6&lPriest":
		if {prestiges::%player's uuid%} is less than 5:
			send "&cThis quest requires prestige 5 to be started." to player
			play sound "entity.villager.no" to player
function tokenChance(p: player):
	set {_uuid} to {_p}'s uuid
	{tokeneligible::%{_uuid}%} is true
	chance of 2%:
		add 1 to {tokens::%{_uuid}%}
function quest(p: player, n: number, d: number):
	set {_uuid} to {_p}'s uuid
	if {_n} is 1:
		set {questmode.%{_uuid}%} to true
		apply potion of blindness to {_p} for 100 second
		loop {_d} times:
			wait 1 second
		execute console command "effect clear %{_p}%"
		set {questmode.%{_uuid}%} to false
	else:
		set {questmode.%{_uuid}%} to false
		execute console command "effect clear %{_p}%"
command nameless:
	permission: op
	trigger:
		set {nameless::%player's uuid%} to true
		
on any movement:
	if {questmode.%player's uuid%} is true:
		cancel event
on right click with book:
	cancel event
on drop:
	if player does not have permission "egg.drop":
		cancel event
on inventory click:
	if player does not have permission "egg.inventory":
		cancel event