on first join:
	set join message to "&7[&a+&7] %player% &8(&7%number of all offline players%&8)"

on join:
	set join message to "&7[&a+&7] %player%"

on quit:
	set quit message to "&7[&c-&7] %player%"

on chat:
	if player has permission "staff":
		set chat format to "%player's prefix% %player's name% &8» &f%formatted message%"
	else:
		set chat format to "%player's prefix% %player's name% &8» &7%message%"

