function formatNum(n: number) :: text:
	loop split "Sx,21|Qi,18|Qa,15|T,12|B,9|M,6|K,3" at "|":
		set {_s::*} to split loop-value at ","
		{_n} >= 10 ^ {_s::2} parsed as number
		return "%(floor({_n} / 10 ^ (({_s::2} parsed as number) - 2)) / 100)%%{_s::1}%"
	return "%{_n}%"

function teleportPlayer(p: player, x: number, y: number, z: number, pitch: number, yaw: number, world: text):
	teleport {_p} to location({_x}, {_y}, {_z}, {_world}, {_yaw}, {_pitch})