on block trample:
	cancel event

on hunger bar change:
	cancel event

on damage:
	attacker's gamemode is not creative
	cancel event

on right click on item frame:
	player's gamemode is not creative
	cancel event

on right click:
	player's gamemode is not creative
	event-block is set
	"%event-block%" contains "potted "
	cancel event

on break:
	player's gamemode is not creative
	cancel event

on portal:
	cancel event